# fly.toml app configuration file generated for ai-commander-yh2826 on 2026-06-08T18:31:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-commander-yh2826'
primary_region = 'sin'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
