// ============================================================
// AI Commander — Map Data (Hardcoded Region Graph)
// Regions, Chokepoints, Facilities, Fronts for "Dual-Island Strait"
// This is the structured data LLM uses to understand the map.
// ============================================================

import type { Region, Chokepoint, Facility, Front } from "@ai-commander/shared";

// ──────────────────────────────────────────────
// Regions (~35 regions covering the 200x150 map)
// ──────────────────────────────────────────────

export const REGIONS: Region[] = [
  // === Player Side (North) ===
  {
    id: "player_base",
    name: "Player Base",
    bbox: [75, 0, 125, 15],
    terrainMix: { urban: 0.6, road: 0.2, plains: 0.2 },
    passability: { armor: true, infantry: true, naval: false },
    chokepoints: [],
    adjacent: ["north_plains_west", "north_city", "north_plains_east"],
    strategicValue: ["headquarters", "production"],
    facilities: ["player_hq", "player_barracks", "player_shipyard", "player_airfield", "player_radar"],
  },
  {
    id: "north_forest",
    name: "North Forest",
    bbox: [10, 15, 55, 50],
    terrainMix: { forest: 0.6, plains: 0.3, road: 0.1 },
    passability: { armor: false, infantry: true, naval: false },
    chokepoints: [],
    adjacent: ["player_base", "north_plains_west", "west_bridge_approach_n"],
    strategicValue: ["concealment"],
    facilities: [],
  },
  {
    id: "north_plains_west",
    name: "North Plains (West)",
    bbox: [10, 15, 55, 30],
    terrainMix: { plains: 0.6, road: 0.2, forest: 0.2 },
    passability: { armor: true, infantry: true, naval: false },
    chokepoints: [],
    adjacent: ["player_base", "north_forest", "west_bridge_approach_n"],
    strategicValue: [],
    facilities: [],
  },
  {
    id: "north_city",
    name: "North Central City",
    bbox: [80, 25, 120, 55],
    terrainMix: { urban: 0.5, road: 0.3, plains: 0.2 },
    passability: { armor: true, infantry: true, naval: false },
    chokepoints: [],
    adjacent: ["player_base", "center_bridge_approach_n", "north_plains_east", "north_plains_west"],
    strategicValue: ["urban_defense"],
    facilities: ["repair_station_north"],
  },
  {
    id: "north_hills",
    name: "Northeast Hills",
    bbox: [125, 8, 185, 45],
    terrainMix: { hills: 0.6, plains: 0.3, road: 0.1 },
    passability: { armor: true, infantry: true, naval: false },
    chokepoints: [],
    adjacent: ["north_plains_east", "east_bridge_approach_n"],
    strategicValue: ["high_ground"],
    facilities: [],
  },
  {
    id: "north_plains_east",
    name: "North Plains (East)",
    bbox: [120, 15, 185, 55],
    terrainMix: { plains: 0.5, hills: 0.3, road: 0.2 },
    passability: { armor: true, infantry: true, naval: false },
    chokepoints: [],
    adjacent: ["player_base", "north_city", "north_hills", "east_bridge_approach_n"],
    strategicValue: [],
    facilities: [],
  },

  // === Bridge Approaches (North) ===
  {
    id: "west_bridge_approach_n",
    name: "West Bridge (North Approach)",
    bbox: [30, 50, 55, 65],
    terrainMix: { plains: 0.5, road: 0.3, shallow_water: 0.2 },
    passability: { armor: true, infantry: true, naval: false },
    chokepoints: ["bridge_west"],
    adjacent: ["north_plains_west", "north_forest", "west_bridge_zone"],
    strategicValue: ["bridge_approach"],
    facilities: [],
  },
  {
    id: "center_bridge_approach_n",
    name: "Center Bridge (North Approach)",
    bbox: [85, 50, 115, 65],
    terrainMix: { plains: 0.4, road: 0.3, urban: 0.2, shallow_water: 0.1 },
    passability: { armor: true, infantry: true, naval: false },
    chokepoints: ["bridge_center"],
    adjacent: ["north_city", "center_bridge_zone"],
    strategicValue: ["bridge_approach"],
    facilities: ["comm_tower_center"],
  },
  {
    id: "east_bridge_approach_n",
    name: "East Bridge (North Approach)",
    bbox: [145, 50, 175, 65],
    terrainMix: { plains: 0.5, road: 0.3, shallow_water: 0.2 },
    passability: { armor: true, infantry: true, naval: false },
    chokepoints: ["bridge_east"],
    adjacent: ["north_plains_east", "north_hills", "east_bridge_zone"],
    strategicValue: ["bridge_approach"],
    facilities: [],
  },

  // === Bridge Zones (the bridges themselves) ===
  {
    id: "west_bridge_zone",
    name: "West Bridge",
    bbox: [35, 60, 48, 90],
    terrainMix: { bridge: 0.4, deep_water: 0.3, shallow_water: 0.3 },
    passability: { armor: true, infantry: true, naval: false },
    chokepoints: ["bridge_west"],
    adjacent: ["west_bridge_approach_n", "west_bridge_approach_s", "strait_west"],
    strategicValue: ["chokepoint", "bridge"],
    facilities: [],
  },
  {
    id: "center_bridge_zone",
    name: "Center Bridge",
    bbox: [93, 60, 108, 90],
    terrainMix: { bridge: 0.4, deep_water: 0.3, shallow_water: 0.3 },
    passability: { armor: true, infantry: true, naval: false },
    chokepoints: ["bridge_center"],
    adjacent: ["center_bridge_approach_n", "center_bridge_approach_s", "strait_center"],
    strategicValue: ["chokepoint", "bridge"],
    facilities: [],
  },
  {
    id: "east_bridge_zone",
    name: "East Bridge",
    bbox: [155, 60, 168, 90],
    terrainMix: { bridge: 0.4, deep_water: 0.3, shallow_water: 0.3 },
    passability: { armor: true, infantry: true, naval: false },
    chokepoints: ["bridge_east"],
    adjacent: ["east_bridge_approach_n", "east_bridge_approach_s", "strait_east"],
    strategicValue: ["chokepoint", "bridge"],
    facilities: [],
  },

  // === Strait (Water Zones) ===
  {
    id: "strait_west",
    name: "Strait (West)",
    bbox: [8, 60, 55, 90],
    terrainMix: { deep_water: 0.7, shallow_water: 0.3 },
    passability: { armor: false, infantry: false, naval: true },
    chokepoints: [],
    adjacent: ["west_bridge_zone", "strait_center"],
    strategicValue: ["naval_zone"],
    facilities: [],
  },
  {
    id: "strait_center",
    name: "Strait (Center)",
    bbox: [55, 60, 145, 90],
    terrainMix: { deep_water: 0.8, shallow_water: 0.2 },
    passability: { armor: false, infantry: false, naval: true },
    chokepoints: [],
    adjacent: ["strait_west", "strait_east", "west_bridge_zone", "center_bridge_zone", "east_bridge_zone"],
    strategicValue: ["naval_zone", "shipping_lane"],
    facilities: ["radar_strait"],
  },
  {
    id: "strait_east",
    name: "Strait (East)",
    bbox: [145, 60, 192, 90],
    terrainMix: { deep_water: 0.7, shallow_water: 0.3 },
    passability: { armor: false, infantry: false, naval: true },
    chokepoints: [],
    adjacent: ["east_bridge_zone", "strait_center"],
    strategicValue: ["naval_zone"],
    facilities: [],
  },

  // === Bridge Approaches (South) ===
  {
    id: "west_bridge_approach_s",
    name: "West Bridge (South Approach)",
    bbox: [30, 85, 55, 100],
    terrainMix: { plains: 0.4, hills: 0.3, shallow_water: 0.2, road: 0.1 },
    passability: { armor: true, infantry: true, naval: false },
    chokepoints: ["bridge_west"],
    adjacent: ["west_bridge_zone", "south_hills"],
    strategicValue: ["bridge_approach"],
    facilities: [],
  },
  {
    id: "center_bridge_approach_s",
    name: "Center Bridge (South Approach)",
    bbox: [80, 85, 120, 105],
    terrainMix: { plains: 0.4, road: 0.3, urban: 0.2, shallow_water: 0.1 },
    passability: { armor: true, infantry: true, naval: false },
    chokepoints: ["bridge_center"],
    adjacent: ["center_bridge_zone", "south_city"],
    strategicValue: ["bridge_approach"],
    facilities: [],
  },
  {
    id: "east_bridge_approach_s",
    name: "East Bridge (South Approach)",
    bbox: [145, 85, 175, 105],
    terrainMix: { plains: 0.4, forest: 0.3, shallow_water: 0.2, road: 0.1 },
    passability: { armor: true, infantry: true, naval: false },
    chokepoints: ["bridge_east"],
    adjacent: ["east_bridge_zone", "south_forest"],
    strategicValue: ["bridge_approach"],
    facilities: [],
  },

  // === Enemy Side (South) ===
  {
    id: "south_hills",
    name: "South Hills",
    bbox: [10, 90, 75, 120],
    terrainMix: { hills: 0.6, plains: 0.2, forest: 0.1, road: 0.1 },
    passability: { armor: true, infantry: true, naval: false },
    chokepoints: [],
    adjacent: ["west_bridge_approach_s", "south_city", "far_south_swamp"],
    strategicValue: ["high_ground"],
    facilities: ["fuel_depot_south"],
  },
  {
    id: "south_city",
    name: "South Central City",
    bbox: [80, 95, 120, 125],
    terrainMix: { urban: 0.5, road: 0.3, plains: 0.2 },
    passability: { armor: true, infantry: true, naval: false },
    chokepoints: [],
    adjacent: ["center_bridge_approach_s", "south_hills", "south_forest", "far_south_plains"],
    strategicValue: ["urban_defense"],
    facilities: [],
  },
  {
    id: "south_forest",
    name: "South Forest",
    bbox: [115, 95, 175, 135],
    terrainMix: { forest: 0.6, plains: 0.2, hills: 0.1, road: 0.1 },
    passability: { armor: false, infantry: true, naval: false },
    chokepoints: [],
    adjacent: ["east_bridge_approach_s", "south_city", "far_south_plains"],
    strategicValue: ["concealment"],
    facilities: ["ammo_depot_south"],
  },
  {
    id: "far_south_swamp",
    name: "Far South Swamp",
    bbox: [8, 118, 65, 148],
    terrainMix: { swamp: 0.6, plains: 0.2, road: 0.1, forest: 0.1 },
    passability: { armor: false, infantry: true, naval: false },
    chokepoints: [],
    adjacent: ["south_hills", "far_south_plains"],
    strategicValue: ["flanking_route"],
    facilities: [],
  },
  {
    id: "far_south_plains",
    name: "Far South Plains",
    bbox: [65, 120, 140, 140],
    terrainMix: { plains: 0.5, road: 0.3, swamp: 0.1, urban: 0.1 },
    passability: { armor: true, infantry: true, naval: false },
    chokepoints: [],
    adjacent: ["south_city", "south_forest", "far_south_swamp", "enemy_base"],
    strategicValue: [],
    facilities: ["rail_hub_south"],
  },
  {
    id: "enemy_base",
    name: "Enemy Base",
    bbox: [75, 135, 125, 150],
    terrainMix: { urban: 0.6, road: 0.2, plains: 0.2 },
    passability: { armor: true, infantry: true, naval: false },
    chokepoints: [],
    adjacent: ["far_south_plains", "south_city", "south_forest"],
    strategicValue: ["headquarters", "production"],
    facilities: ["enemy_hq", "enemy_barracks", "enemy_shipyard", "enemy_airfield", "enemy_radar"],
  },
];

// ──────────────────────────────────────────────
// Chokepoints (3 bridges crossing the strait)
// ──────────────────────────────────────────────

export const CHOKEPOINTS: Chokepoint[] = [
  {
    id: "bridge_west",
    name: "West Bridge",
    position: { x: 41, y: 75 },
    type: "bridge",
    connects: ["west_bridge_approach_n", "west_bridge_approach_s"],
    passableFor: ["armor", "infantry"],
    destructible: true,
    hp: 500,
    maxHp: 500,
  },
  {
    id: "bridge_center",
    name: "Center Bridge",
    position: { x: 101, y: 75 },
    type: "bridge",
    connects: ["center_bridge_approach_n", "center_bridge_approach_s"],
    passableFor: ["armor", "infantry"],
    destructible: true,
    hp: 500,
    maxHp: 500,
  },
  {
    id: "bridge_east",
    name: "East Bridge",
    position: { x: 161, y: 75 },
    type: "bridge",
    connects: ["east_bridge_approach_n", "east_bridge_approach_s"],
    passableFor: ["armor", "infantry"],
    destructible: true,
    hp: 500,
    maxHp: 500,
  },
];

// ──────────────────────────────────────────────
// Facilities — buildings on the map
// ──────────────────────────────────────────────

export const FACILITIES: Facility[] = [
  // === Player Base Facilities ===
  {
    id: "player_hq",
    name: "Player HQ",
    type: "headquarters",
    tags: ["HQ", "headquarters", "main base", "command center"],
    position: { x: 100, y: 5 },
    team: "player",
    hp: 2000,
    maxHp: 2000,
    regionId: "player_base",
    strategicEffect: "Game over if destroyed",
    captureProgress: 0,
    capturingTeam: null,
  },
  {
    id: "player_barracks",
    name: "Player Barracks",
    type: "barracks",
    tags: ["barracks", "infantry", "ground production"],
    position: { x: 90, y: 8 },
    team: "player",
    hp: 500,
    maxHp: 500,
    regionId: "player_base",
    strategicEffect: "Produces ground units",
    captureProgress: 0,
    capturingTeam: null,
  },
  {
    id: "player_shipyard",
    name: "Player Shipyard",
    type: "shipyard",
    tags: ["shipyard", "dock", "naval production"],
    position: { x: 85, y: 12 },
    team: "player",
    hp: 500,
    maxHp: 500,
    regionId: "player_base",
    strategicEffect: "Produces naval units",
    captureProgress: 0,
    capturingTeam: null,
  },
  {
    id: "player_airfield",
    name: "Player Airfield",
    type: "airfield",
    tags: ["airfield", "airport", "air production"],
    position: { x: 110, y: 8 },
    team: "player",
    hp: 500,
    maxHp: 500,
    regionId: "player_base",
    strategicEffect: "Produces air units",
    captureProgress: 0,
    capturingTeam: null,
  },
  {
    id: "player_radar",
    name: "Player Radar",
    type: "radar",
    tags: ["radar", "early warning"],
    position: { x: 100, y: 12 },
    team: "player",
    hp: 300,
    maxHp: 300,
    regionId: "player_base",
    strategicEffect: "Base 20-tile vision + minimap enemy detection",
    captureProgress: 0,
    capturingTeam: null,
  },

  // === Neutral Capturable Facilities ===
  {
    id: "comm_tower_center",
    name: "Communication Tower",
    type: "comm_tower",
    tags: ["comm tower", "signal", "communication", "intel"],
    position: { x: 100, y: 55 },
    team: "neutral",
    hp: 300,
    maxHp: 300,
    regionId: "center_bridge_approach_n",
    strategicEffect: "+20 Intel/30s + area full vision",
    captureProgress: 0,
    capturingTeam: null,
  },
  {
    id: "repair_station_north",
    name: "Repair Station",
    type: "repair_station",
    tags: ["repair", "maintenance", "heal"],
    position: { x: 95, y: 40 },
    team: "neutral",
    hp: 300,
    maxHp: 300,
    regionId: "north_city",
    strategicEffect: "Nearby units +2% HP/s",
    captureProgress: 0,
    capturingTeam: null,
  },
  {
    id: "radar_strait",
    name: "Strait Radar Station",
    type: "radar",
    tags: ["radar", "naval radar", "strait watch"],
    position: { x: 100, y: 75 },
    team: "neutral",
    hp: 300,
    maxHp: 300,
    regionId: "strait_center",
    strategicEffect: "Minimap shows enemy fleet positions",
    captureProgress: 0,
    capturingTeam: null,
  },
  {
    id: "fuel_depot_south",
    name: "South Oil Depot",
    type: "fuel_depot",
    tags: ["oil depot", "fuel", "oil", "energy"],
    position: { x: 45, y: 105 },
    team: "neutral",
    hp: 400,
    maxHp: 400,
    regionId: "south_hills",
    strategicEffect: "+30 Fuel/30s",
    captureProgress: 0,
    capturingTeam: null,
  },
  {
    id: "ammo_depot_south",
    name: "South Ammo Depot",
    type: "ammo_depot",
    tags: ["ammo depot", "ammunition", "munitions"],
    position: { x: 140, y: 115 },
    team: "neutral",
    hp: 400,
    maxHp: 400,
    regionId: "south_forest",
    strategicEffect: "+25 Ammo/30s",
    captureProgress: 0,
    capturingTeam: null,
  },
  {
    id: "rail_hub_south",
    name: "Railway Hub",
    type: "rail_hub",
    tags: ["railway", "rail hub", "train", "logistics"],
    position: { x: 100, y: 130 },
    team: "neutral",
    hp: 400,
    maxHp: 400,
    regionId: "far_south_plains",
    strategicEffect: "+25 Ammo/30s + supply transport -30%",
    captureProgress: 0,
    capturingTeam: null,
  },

  // === Enemy Base Facilities ===
  {
    id: "enemy_hq",
    name: "Enemy HQ",
    type: "headquarters",
    tags: ["enemy HQ", "enemy headquarters", "enemy command"],
    position: { x: 100, y: 143 },
    team: "enemy",
    hp: 2000,
    maxHp: 2000,
    regionId: "enemy_base",
    strategicEffect: "Game over if destroyed",
    captureProgress: 0,
    capturingTeam: null,
  },
  {
    id: "enemy_barracks",
    name: "Enemy Barracks",
    type: "barracks",
    tags: ["enemy barracks"],
    position: { x: 90, y: 140 },
    team: "enemy",
    hp: 500,
    maxHp: 500,
    regionId: "enemy_base",
    strategicEffect: "Produces ground units",
    captureProgress: 0,
    capturingTeam: null,
  },
  {
    id: "enemy_shipyard",
    name: "Enemy Shipyard",
    type: "shipyard",
    tags: ["enemy shipyard"],
    position: { x: 85, y: 145 },
    team: "enemy",
    hp: 500,
    maxHp: 500,
    regionId: "enemy_base",
    strategicEffect: "Produces naval units",
    captureProgress: 0,
    capturingTeam: null,
  },
  {
    id: "enemy_airfield",
    name: "Enemy Airfield",
    type: "airfield",
    tags: ["enemy airfield"],
    position: { x: 110, y: 140 },
    team: "enemy",
    hp: 500,
    maxHp: 500,
    regionId: "enemy_base",
    strategicEffect: "Produces air units",
    captureProgress: 0,
    capturingTeam: null,
  },
  {
    id: "enemy_radar",
    name: "Enemy Radar",
    type: "radar",
    tags: ["enemy radar"],
    position: { x: 100, y: 145 },
    team: "enemy",
    hp: 300,
    maxHp: 300,
    regionId: "enemy_base",
    strategicEffect: "Enemy early warning",
    captureProgress: 0,
    capturingTeam: null,
  },
];

// ──────────────────────────────────────────────
// Fronts — 5 battle lines
// ──────────────────────────────────────────────

export const FRONTS: Front[] = [
  {
    id: "front_north",
    name: "1. North Plains",
    regionIds: ["north_plains_west", "north_plains_east", "north_hills", "west_bridge_approach_n"],
    playerPower: 0,
    enemyPower: 0,
    enemyPowerKnown: false,
    engagementIntensity: 0,
    supplyStatus: "OK",
    keyEvents: [],
  },
  {
    id: "front_center",
    name: "2. Central City",
    regionIds: ["north_city", "center_bridge_approach_n", "center_bridge_zone", "center_bridge_approach_s"],
    playerPower: 0,
    enemyPower: 0,
    enemyPowerKnown: false,
    engagementIntensity: 0,
    supplyStatus: "OK",
    keyEvents: [],
  },
  {
    id: "front_strait",
    name: "3. Strait Waters",
    regionIds: ["strait_west", "strait_center", "strait_east"],
    playerPower: 0,
    enemyPower: 0,
    enemyPowerKnown: false,
    engagementIntensity: 0,
    supplyStatus: "OK",
    keyEvents: [],
  },
  {
    id: "front_south",
    name: "4. South Hills",
    regionIds: ["south_hills", "south_city", "south_forest", "west_bridge_approach_s", "east_bridge_approach_s"],
    playerPower: 0,
    enemyPower: 0,
    enemyPowerKnown: false,
    engagementIntensity: 0,
    supplyStatus: "OK",
    keyEvents: [],
  },
  {
    id: "front_far_south",
    name: "5. Far South",
    regionIds: ["far_south_swamp", "far_south_plains", "enemy_base"],
    playerPower: 0,
    enemyPower: 0,
    enemyPowerKnown: false,
    engagementIntensity: 0,
    supplyStatus: "OK",
    keyEvents: [],
  },
];

// ──────────────────────────────────────────────
// Front camera positions (tile coords for keys 1-5)
// ──────────────────────────────────────────────

export const FRONT_CAMERA_TARGETS: Record<string, { x: number; y: number }> = {
  front_north:     { x: 80,  y: 30 },
  front_center:    { x: 100, y: 60 },
  front_strait:    { x: 100, y: 75 },
  front_south:     { x: 90,  y: 105 },
  front_far_south: { x: 90,  y: 130 },
};
