export { applyOrders, applyEnemyOrders, replaceProvisionalOrders, applyPlayerCommands, releaseManualOverride } from "./applyOrders";
export { tick, canUnitEnterTile } from "./sim";
export { calculateDamage, processCombat } from "./combat";
export { processRegen } from "./regen";
export { createFogState, updateFog } from "./fog";
export { processEconomy, enqueueProduction, canUnitMove, isMechanized } from "./economy";
export { processEnemyAI, resetEnemyAITimer, resetEnemyProdToggle, resetAttackWaveState } from "./enemyAI";
export { processAutoBehavior, resetAutoBehaviorTimer } from "./autoBehavior";
export { processMissions, createMission, resetMissionCounter } from "./missions";
export type { CreateMissionOpts } from "./missions";
export { createDefaultStyle, updateStyleParam } from "./styleEngine";
export { updateGamePhase, checkGameOver, applyEndgamePressure, resetWarPhaseTimers } from "./warPhase";
export { resolveIntent, isIntentSupported, findFront, resolveRoute, resolveRouteChain } from "./tacticalPlanner";
export { getFormationOffset, computeHeading } from "./formation";
export type { FormationStyle } from "./formation";
export type { ResolveResult } from "./tacticalPlanner";
export { buildDigest } from "./intelDigest";
export { buildBattleContextV2 } from "./battleContext";
export { processReportSignals, drainReportEvents, resetReportSignals } from "./reportSignals";
export { createInitialGameState } from "./scenario";
export { processDefensiveAI, resetDefensiveAITimer } from "./scenario/elAlamein";
export { checkDoctrines, cancelDoctrine } from "./doctrine";
export { findBestReinforcements, generateCrisisCard } from "./crisisResponse";
export type { ReinforceCandidate } from "./crisisResponse";
export { updateTasks, computeTaskPriority } from "./taskTracker";
export { updateBattleMarkers } from "./battleAwareness";
export { processAdvisorTriggers } from "./advisorTrigger";
export type { AdvisorTriggerResult } from "./advisorTrigger";
