export { applyOrders, applyEnemyOrders, replaceProvisionalOrders, applyPlayerCommands, releaseManualOverride } from "./applyOrders";
export { tick, canUnitEnterTile } from "./sim";
export { calculateDamage, processCombat } from "./combat";
export { createFogState, updateFog } from "./fog";
export { processEconomy, enqueueProduction, canUnitMove, isMechanized } from "./economy";
export { processEnemyAI, resetEnemyAITimer, resetEnemyProdToggle } from "./enemyAI";
export { processAutoBehavior, resetAutoBehaviorTimer } from "./autoBehavior";
export { processMissions, createMission, resetMissionCounter } from "./missions";
export type { CreateMissionOpts } from "./missions";
export { createDefaultStyle, updateStyleParam } from "./styleEngine";
export { updateGamePhase, checkGameOver, applyEndgamePressure, resetWarPhaseTimers } from "./warPhase";
export { resolveIntent, isIntentSupported, findFront } from "./tacticalPlanner";
export type { ResolveResult } from "./tacticalPlanner";
export { buildDigest } from "./intelDigest";
export { processReportSignals, drainReportEvents, resetReportSignals } from "./reportSignals";
export { createInitialGameState } from "./scenario";
export { checkDoctrines, cancelDoctrine } from "./doctrine";
export { findBestReinforcements, generateCrisisCard } from "./crisisResponse";
export type { ReinforceCandidate } from "./crisisResponse";
export { updateTasks, computeTaskPriority } from "./taskTracker";
export { updateBattleMarkers } from "./battleAwareness";
